command ::= item_command
    | table_command

item_command ::= select_command
    | insert_command
    | update_command
    | delete_command

table_command ::=
    | describe_command
    | create_command
    | alter_command
    | drop_command
    | show_command

create_command ::=
    ( "CREATE" | "create" ) (character_set)+
    "("((character_set)+,)+")"
    ("WITH"|"with") ("VALUES"|"values")
    "("((character_set)+,)+")"

select_command ::=
    ("SELECT"|"select")
    ("*"|(character_set)+)
    ("FROM"|"from")
    (character_set)+
    [("WHERE"|"where") condition]
    [("LIMIT"|"limit") (numeric)+]

insert_command ::=
    ( "INSERT" | "insert" )
    ("INTO"|"into")
    (character_set)+
    "("((character_set)+,)+")"
    ("VALUES"|"values")
    "("((character_set)+,)+")"

update_command ::=
    ("UPDATE"|update")
    (character_set)+
    ("SET"|"set")
    (character_set)+
    "="
    (character_set)+
    [("WHERE"|"where") condition]

delete_command ::=
    ("DELETE"|"delete")
    ("FROM"|"from")
    (character_set)+
    [("WHERE"|"where") condition]

describe_command ::=
    ("DESCRIBE"|"describe")
    (character_set)+

drop_command ::=
    ("DESCRIBE"|"describe")
    (character_set)+

show_command ::=
    ("SHOW"|"show")
    ("TABLES"|"tables")

alter_command ::=
    ("ALTER"|alter")
    ("TABLE"|table")
    (character_set)+
    ("SET"|"set")
    (character_set)+
    "="
    (character_set)

condition ::=
    (character_set)+
    (["<"|">"|"!"]=|["<"|">"|"="])
    (character_set)+
    [(("AND"|"and")|("OR"|"or"))
    (character_set)+
    (["<"|">"|"!"]=|["<"|">"|"="])
    (character_set)+]

character_set ::=
    "a"|"b"|"c"|"d"|"e"|"f"|"g"|"h"|"i"|"j"|"k"|"l"|"m"
    "n"|"o"|"p"|"q"|"r"|"s"|"t"|"u"|"v"|"w"|"x"|"y"|"z"
    |"A"|"B"|"C"|"D"|"E"|"F"|"G"|"H"|"I"|"J"|"K"|"L"|"M"
    |"N"|"O"|"P"|"Q"|"R"|"S"|"T"|"U"|"V"|"W"|"X"|"Y"|"Z"
    |"0"|"1"|"2"|"3"|"4"|"5"|"6"|"7"|"8"|"9"
    |"-"|"_"|"("|")"|"."|","|"""|"/"|"\"|"@"|"#"|"~"|"|"
    |"*"|"&"|"%"|"$"|"£"|"!"|"+"|"?"|">"|"<"|"="

numeric ::=
    "0"|"1"|"2"|"3"|"4"|"5"|"6"|"7"|"8"|"9"
